[package]
name = "makepad_image_manipulation"
version = "0.1.0"
edition = "2021"

[dependencies]
makepad-platform = { path = "../makepad/platform", version = "0.3.0" }
makepad-widgets = { path = "../makepad/widgets", version = "0.3.0" }